site_name: LynrieScoop Documentation
site_description: Comprehensive documentation for the LynrieScoop Cinema Web Application
site_author: LynrieScoop Team
repo_url: https://github.com/YourUsername/LynrieScoop.git
copyright: Copyright &copy; 2025 LynrieScoop Team

# Set docs_dir to the root docs directory
docs_dir: ../../docs

theme:
  name: material
  locale: en
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  # logo: assets/logo.png
  # favicon: assets/favicon.ico

nav:
  - Home: index.md #? README.md gets renamed to index.md in Dockerfile
  - Architecture:
      - System Architecture: architecture.md
      - API Reference: api-reference.md
      - Authentication System: authentication.md
      - MQTT Integration: mqtt-integration.md
  - Implementation:
      - Frontend Guide: frontend-guide.md
      - Backend Guide: backend-guide.md
      - Code Quality Tools: code-quality-tools.md
  - Operations:
      - Deployment Guide: deployment-guide.md
      - Documentation Guide: documentation-guide.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
