name: Backend Linting

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-lint.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort mypy

      - name: Run Black formatter check
        working-directory: ./backend
        run: python -m black --check .

      - name: Run flake8
        working-directory: ./backend
        run: python -m flake8

      - name: Run isort check
        working-directory: ./backend
        run: python -m isort --check .

      - name: Run mypy type checker
        working-directory: ./backend
        run: python -m mypy .
