name: Lint Code Base

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort mypy

      - name: Run Black formatter check
        working-directory: ./backend
        run: python -m black --check .

      - name: Run flake8
        working-directory: ./backend
        run: python -m flake8

      - name: Run isort check
        working-directory: ./backend
        run: python -m isort --check .

      - name: Run mypy type checker
        working-directory: ./backend
        run: python -m mypy .

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root dependencies
        run: npm install --no-cache

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install --no-cache

      - name: Run ESLint
        working-directory: ./frontend
        run: npx eslint "**/*.{js,ts}" --max-warnings=0

      - name: Type-check TypeScript
        working-directory: ./frontend
        run: npx tsc --noEmit
